#include <stdio.h>
#include <string.h>

#include "pico/stdlib.h"
#include "pico/unique_id.h"
#include "hardware/clocks.h"
#include "hardware/vreg.h"
#include "hardware/watchdog.h"
#include "hardware/adc.h"
#include "hardware/structs/xip.h"
#include "hardware/structs/qmi.h"
#include "hardware/regs/qmi.h"

#include "mbedtls/version.h"

#include "version.h"
#include "build_info.h"   /* generated by CMake */

#ifndef BENCH_CODE_LOC
#define BENCH_CODE_LOC "unknown"
#endif

#if defined(__riscv)
#define ARCH_STR "RISC-V Hazard3"
#else
#define ARCH_STR "Arm Cortex-M33"
#endif

#if defined(PICO_SDK_VERSION_STRING)
#define SDK_STR PICO_SDK_VERSION_STRING
#else
#define SDK_STR "unknown"
#endif

/* ---- individual readings ------------------------------------------------ */

uint32_t bench_qmi_clkdiv(void)
{
    uint32_t d = (qmi_hw->m[0].timing & QMI_M0_TIMING_CLKDIV_BITS) >> QMI_M0_TIMING_CLKDIV_LSB;
    return d ? d : 256u;   /* CLKDIV 0 encodes 256 */
}

uint32_t bench_qmi_rxdelay(void)
{
    return (qmi_hw->m[0].timing & QMI_M0_TIMING_RXDELAY_BITS) >> QMI_M0_TIMING_RXDELAY_LSB;
}

uint32_t bench_flash_sck_khz(void)
{
    return (uint32_t)(clock_get_hz(clk_sys) / 1000u) / bench_qmi_clkdiv();
}

uint16_t bench_vreg_mv(void)
{
    uint32_t v = (uint32_t)vreg_get_voltage();
    /* 0b00000..0b01111 is a linear 0.55 V .. 1.30 V ladder in 50 mV steps. */
    if (v <= 15) return (uint16_t)(550 + v * 50);
    switch (v) {
        case 16: return 1350;
        case 17: return 1400;
        case 18: return 1500;
        case 19: return 1600;
        case 20: return 1650;
        case 21: return 1700;
        case 22: return 1800;
        case 23: return 1900;
        default: return 0;   /* unknown encoding */
    }
}

/* The RP2350 die temperature sensor read full scale on this board across an
 * entire sweep, so thermal reporting is deliberately not implemented. VSYS is
 * measured instead: at high clock and raised core voltage a sagging supply
 * looks exactly like an unstable core, and this tells the two apart. */
uint16_t bench_vsys_mv(void)
{
#ifdef PICO_VSYS_PIN
    adc_gpio_init(PICO_VSYS_PIN);
    adc_select_input(PICO_VSYS_PIN - 26);
    busy_wait_us(10);
    (void)adc_read();
    uint32_t raw = adc_read();
    /* board divides VSYS by 3 into the ADC */
    return (uint16_t)((raw * 3300u * 3u) / 4096u);
#else
    return 0;
#endif
}

/* XIP cache instrumentation: hit and access counters, cleared by writing. */
void bench_xip_reset(void)
{
    xip_ctrl_hw->ctr_hit = 0;
    xip_ctrl_hw->ctr_acc = 0;
}
void bench_xip_read(uint32_t *hit, uint32_t *acc)
{
    *hit = xip_ctrl_hw->ctr_hit;
    *acc = xip_ctrl_hw->ctr_acc;
}
/* Hit rate in tenths of a percent; 1000 = every access hit the cache. */
uint32_t bench_xip_hit_permille(uint32_t hit, uint32_t acc)
{
    return acc ? (uint32_t)(((uint64_t)hit * 1000u) / acc) : 0u;
}

/* ---- banners ------------------------------------------------------------ */

void bench_print_build_info(const char *program_name)
{
    char board_id[2 * PICO_UNIQUE_BOARD_ID_SIZE_BYTES + 1];
    pico_get_unique_board_id_string(board_id, sizeof(board_id));

    printf("\n=====================================================================\n");
    printf(" RP2350 crypto benchmark suite\n");
    printf(" firmware  : %s v%s  build %s (%s)\n",
           program_name, BENCH_VERSION_STRING, BUILD_STAMP, BUILD_ID);
    printf(" compiled  : %s %s   GCC %s\n", __DATE__, __TIME__, __VERSION__);
    printf(" core      : %s\n", ARCH_STR);
    printf(" chip      : RP2350  chip_version %u  rom_version %u\n",
           rp2350_chip_version(), rp2350_rom_version());
    printf(" board id  : %s\n", board_id);
    printf(" sdk       : %s   Mbed TLS %s (%s)\n",
           SDK_STR, MBEDTLS_VERSION_STRING, LIB_MBEDTLS_COMMIT);
    printf(" libs      : micro-ecc %s   Monocypher %s   p256-m (in Mbed TLS)\n",
           LIB_MICROECC_COMMIT, LIB_MONOCYPHER_COMMIT);
    printf("             mlkem-native %s (ML-KEM 512/768/1024, portable C)\n",
           LIB_MLKEM_COMMIT);
    printf("             mldsa-native %s (ML-DSA 44/65/87, reduced-RAM C)\n",
           LIB_MLDSA_COMMIT);
    printf(" options   : %s code=%s\n", BUILD_OPTIONS, BENCH_CODE_LOC);
    printf("---------------------------------------------------------------------\n");
}

void bench_print_runtime_state(void)
{
    uint32_t sys_khz  = (uint32_t)(clock_get_hz(clk_sys)  / 1000u);
    uint32_t peri_khz = (uint32_t)(clock_get_hz(clk_peri) / 1000u);
    uint32_t usb_khz  = (uint32_t)(clock_get_hz(clk_usb)  / 1000u);
    uint32_t div      = bench_qmi_clkdiv();
    uint32_t sck      = bench_flash_sck_khz();
    uint16_t mv       = bench_vreg_mv();

    printf(" clk_sys   : %lu.%03lu MHz    clk_peri %lu.%03lu MHz    clk_usb %lu.%03lu MHz\n",
           (unsigned long)(sys_khz / 1000),  (unsigned long)(sys_khz % 1000),
           (unsigned long)(peri_khz / 1000), (unsigned long)(peri_khz % 1000),
           (unsigned long)(usb_khz / 1000),  (unsigned long)(usb_khz % 1000));
    printf(" vreg      : %u.%02u V (VSEL 0x%02x)\n",
           mv / 1000, (mv % 1000) / 10, (unsigned)vreg_get_voltage());
    printf(" flash/QMI : CLKDIV %lu  RXDELAY %lu  -> SCK %lu.%03lu MHz\n",
           (unsigned long)div, (unsigned long)bench_qmi_rxdelay(),
           (unsigned long)(sck / 1000), (unsigned long)(sck % 1000));
    uint16_t vs = bench_vsys_mv();
    printf(" VSYS      : %u.%03u V   (die temp sensor unusable on this board)\n",
           vs / 1000, vs % 1000);
    printf(" last reset: %s\n", watchdog_caused_reboot() ? "WATCHDOG" : "power-on / normal");
    printf("=====================================================================\n");
}

void bench_print_state_line(const char *prefix)
{
    uint32_t sys_khz = (uint32_t)(clock_get_hz(clk_sys) / 1000u);
    uint32_t sck     = bench_flash_sck_khz();
    uint16_t mv      = bench_vreg_mv();
    uint16_t vs      = bench_vsys_mv();

    printf("%s v%s sys=%lu.%03luMHz vreg=%u.%02uV qmi_div=%lu sck=%lu.%03luMHz "
           "rxd=%lu vsys=%u.%03uV\n",
           prefix, BENCH_VERSION_STRING,
           (unsigned long)(sys_khz / 1000), (unsigned long)(sys_khz % 1000),
           mv / 1000, (mv % 1000) / 10,
           (unsigned long)bench_qmi_clkdiv(),
           (unsigned long)(sck / 1000), (unsigned long)(sck % 1000),
           (unsigned long)bench_qmi_rxdelay(), vs / 1000, vs % 1000);
}
